name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.402
    - name: npm install & build & pack (Rin.Frontend)
      working-directory: src/Rin.Frontend
      run: |
        npm install
        npm run build
        npm run pack
    - name: npm install & build & pack (Rin.Mvc.Frontend)
      working-directory: src/Rin.Mvc.Frontend
      run: |
        npm install
        npm run build
    - name: Copy Rin.Mvc.Frontend
      run: |
        mkdir -p src/Rin.Mvc/EmbeddedResources/
        cp -R src/Rin.Mvc.Frontend/build/static/* src/Rin.Mvc/EmbeddedResources/
    - name: dotnet
      run: |
        dotnet restore
        dotnet build -c Release
        dotnet pack -c Release -o $GITHUB_WORKSPACE/artifacts --version-suffix preview.`date +%Y%m%d%H%M%S`
    - uses: actions/upload-artifact@master
      with:
        name: Packages
        path: /github/workspace/artifacts
